### ISSUE TITLE
When searching for slot to generate keys consult the mechanisms

### ISSUE THREAD

**Issue by beldmit** [latchset/pkcs11-provider#140] opened 2022-12-05 18:34 UTC
**Describe the feature**
We should not try to generate new keys using a particular slot if it doesn't support the necessary mechanism.

**Comment by simo5** [comment] 2022-12-05 20:34
This looks like a duplicate of #139 effectively, in general both #139 #140 ask to check that the slot support the desired mechanism for the operation we need to complete.

**Comment by beldmit** [comment] 2022-12-05 20:36
I agree, any of them can be closed.

**Comment by simo5** [comment] 2022-12-05 20:43
Duplicate of #139

**Closed by simo5** 2022-12-05 20:43 UTC
Labels: enhancement
