### ISSUE TITLE
Can this library *create* keys?

### ISSUE THREAD

**Issue by Firstyear** [latchset/pkcs11-provider#303] opened 2023-10-30 02:16 UTC
We can use keys by their pkcs11 url, but can this library be used with openssl to *create* keys into a token? 

If so, some examples would be useful.

**Comment by simo5** [comment] 2023-12-13 13:27
I am not sure there is anything we can do but change openssl here.
The problem is that openssl expects to write out a private key, and we do not export it.

I discussed in the past a store API for writing and deleting, not just for reading. Once that exist we would be able to use the store to write keys, which will allow us to generate keys as session keys, and only write them to the token when the store API gets the request to store the key in the token.

Until then I think the key generation experience will not be optimal via openssl utilities.

**Comment by Firstyear** [comment] 2023-12-13 23:17
Is it worth adding this openssl genpkey example somewhere with the disclaimer about the "error".

**Comment by simo5** [comment] 2023-12-13 23:47
I think it may be worth having a doc with openssl commands that show how rto perform specific operations at some point.
Although there are also better tools to deal with pkcs11 token operations directly, like pkcs11-tool.

Simo.

**Comment by dengert** [comment] 2023-12-14 01:14
> It's possible to create keys on the token using genpkey:

Also depends on the token and the pkcs11 module. They must both support the operations. 

What token and pkcs11 module are you using?

**Comment by 0pq76r** [comment] 2023-12-18 10:26
@dengert
I'm using the pkcs11 interface of a Securosys HSM.

@simo5
Are there any concrete plans for the store API yet. Or is the discussion still ongoing? (Could you please add a link to the discussion thread/mailing list?)

**Comment by simo5** [comment] 2023-12-18 13:54
Unfortunately it was an in-person discussion at a past event and I do not think we filed an issue for that.

**Comment by The-Mule** [comment] 2024-04-30 06:17
Based on the discussion above, we are going to close this one in favor of #301. As mentioned, it is possible to create on the token using openssl with non-standard parameters but it really depends on the token. We recommend using tools working with pkcs11 directly such as p11-kit, p11tool, etc. and we will document all that while addressing #301.

**Closed by The-Mule** 2024-04-30 06:17 UTC
Labels: documentation
