### ISSUE TITLE
Provider does not support CKA_ALWAYS_AUTHENTICATE and CKU_CONTEXT_SPECIFIC 

### ISSUE THREAD

**Issue by dengert** [latchset/pkcs11-provider#238] opened 2023-05-07 20:01 UTC
**Describe the bug**
The provider does not check private key for `CKA_ALWAYS_AUTHENTICATE` and does not then ask user for PIN again to do `C_Login` with `CKU_CONTEXT_SPECIFIC` i.e. acting like FireFox used too. (Caching the pin provider is not good enough unless `C_Login` with `CKU_CONTEXT_SPECIFIC` is used.) Some tokens enforce this on the token.  

**Circumvention**  
  
The following avoids the situation by caching PINS which circumvents the intent of  any policy that would require it. 

OpenSC in `opensc.conf` can `use_pin_caching = true;` and `pin_cache_ignore_user_consent = true;` for older applications that do not support `CKA_ALWAYS_AUTHERNTICATE` the pin caching is then done within OpenSC module. See: https://github.com/OpenSC/OpenSC/blob/master/etc/opensc.conf.example.in#L918-L923 or man opensc.conf 

OpenSC was designed to work with PIN_PAD readers where the pin is never seen by the host computer and thus can never be cached thus requiring the user to prompted for PIN each time. 

ykcs11 also supports `CKA_ALWAYS_AUTHENTICATE` and `CKU_CONTEXT_SPECIFIC`.

**To Reproduce**
See  error https://github.com/latchset/pkcs11-provider/issues/234#issuecomment-1537425203 and a way to circumvent the problem. 

**Expected behavior**
User is prompter to enter PIN before the crypto operation as per:

PIV cards enforce this on the card: https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-73-4.pdf "3.2.1 X.509 Certificate for Digital Signature" "In other words, the PIN or OCC data must be submitted and verified every time immediately before a digital signature key operation. This ensures cardholder participation every time the private key is used for digital signature generation.5" 
Also see the footnote "5" in NIST document. 

The digital sign operation is done in `C_Sign` or `C_SignFinal` 

Other tokens may also require the use of  `CKA_ALWAYS_AUTHENTICATE` and `CKU_CONTEXT_SPECIFIC`.

**Operating environment (please complete the following information):**
 - OS: All
 
**Token and application used (please complete the following information):**
OpenSSL 3.1 with `dgst` to PIV or Yubikey when using `id=%02` which is NIST `9C` key. 
 
**Additional context**

**Comment by simo5** [comment] 2023-05-08 12:24
Duplicate of #42

**Closed** 2023-05-19 18:28 UTC
