### ISSUE TITLE
Do not login the session if already authenticated outside the provider

### ISSUE THREAD

**Issue by manison** [latchset/pkcs11-provider#270] opened 2023-07-31 09:16 UTC
Actually I don't know whether this is a bug or a feature request :) However the libp11 pkcs11 engine once behaved this way and we (ab)used the behavior in our application.

**Describe the feature**
When the provider opens a session for the token for the first time (I believe it's called the login session in the terms of this project) it might be already authenticated if there is another client in the process that uses the PKCS#11 module directly and bypasses the pkcs11-provider. In that case the `C_Login` call that the provider makes is unnecessary.

**Expected behavior**
When the pkcs11-provider opens a new session, it first checks its login state and skips `C_Login` if the session is already authenticated.

**Comment by simo5** [comment] 2023-07-31 13:12
If a login session is already active, we just get an "error" that says the token is already logged in. Why do you need to disable this attempt?

**Comment by manison** [comment] 2023-07-31 14:08
Because even this attempt requires user interaction - in our case a user have to enter the PIN using pinpad, so we try to limit the number of interactions to minimum, ideally the user enters the PIN once at the start of the application.

**Comment by simo5** [comment] 2023-07-31 15:02
It was created for cases where you do not want to log in ... the problem is that I am not sure there is a way to find out if the token is logged in without trying to do a login operation.

**Comment by simo5** [comment] 2023-08-01 12:21
Hadn't thought about that, I will look into it.

**Comment by simo5** [comment] 2023-08-21 17:29
I consider this issue completed since #273 was merged.

**Closed by simo5** 2023-08-21 17:29 UTC
Labels: enhancement
