### ISSUE TITLE
Connection with University network not working after recent update

### ISSUE THREAD

**Issue by joelnoliveira** [latchset/pkcs11-provider#468] opened 2024-11-19 20:17 UTC
**Describe the bug**
The connection with the University networks ("eduroam") stopped working after a recent software update. It tries to connect but eventually gives up, whether wireless or by cable.
The networks settings always worked with the current configuration (remain unchanged).
I created an issue here because some people said that pkcs11-provider was the problem check the discussion [here](https://discussion.fedoraproject.org/t/issue-connecting-to-school-wifi-on-fedora-41/137194/6)

**To Reproduce**
1. Go to Settings
2. Connect to a University network
3. Watch while it tries to make the connection 
4. Watch it fail

**Expected behavior**
Connection with the University networks being successful like it always has been, and still is with other non-University networks.

**Operating environment (please complete the following information):**
 - OS: Fedora Linux 41 (Workstation Edition)
 - Kernel Version: Linux 6.11.8-300.fc41.x86_64

**Additional context**
![Screenshot From 2024-11-19 16-54-52](https://github.com/user-attachments/assets/ead1d777-5688-4f2a-8536-dab2283c5058)

**Comment by simo5** [comment] 2024-11-19 20:37
Duplicate of #467

**Closed** 2024-11-20 22:17 UTC
