### ISSUE TITLE
Version 5.4 causes PEAP/MSCHAPv2 authentication to fail

### ISSUE THREAD

**Issue by aadirave** [latchset/pkcs11-provider#475] opened 2024-11-25 05:42 UTC
**Describe the bug**
On upgrading from version 5.3 to 5.4 on Fedora 41 + GNOME, my wifi stopped connecting to eduroam, which uses PEAP authentication. This issue was also reported on many Fedora forums/Reddit.

**To Reproduce**
1. Upgrade to v5.4
2. Try to connect to a PEAP wifi network

**Expected behavior**
Should have connected to the network without problems.

**Operating environment (please complete the following information):**
 - Fedora 41
 - GNOME

**Token and application used (please complete the following information):**
 - Device: Lenevo IdeaPad w/ Ryzen 9
 - PKCS11 Driver version: 5.4
 - Application: GNOME wifi settings

**Workaround**
Downgrade to v5.3

**Comment by jasperges** [comment] 2024-11-25 07:44
FYI, here is the link to the Fedora bug report: https://bugzilla.redhat.com/show_bug.cgi?id=2326839

**Comment by simo5** [comment] 2024-11-25 13:43
Duplicate of #467

**Closed by simo5** 2024-11-25 13:43 UTC
