### ISSUE TITLE
0.5-4 breaks WPA2 enterprise Wi-Fi on Fedora 41

### ISSUE THREAD

**Issue by winderickxeli** [latchset/pkcs11-provider#470] opened 2024-11-21 08:48 UTC
**Describe the bug**
I can't connect to any WPA2 enterprise protected Wi-Fi connections. When I remove the package or downgrade to 0.5-3 it's working again. I'm unsure to what relevant log information I can further collect.

I was able to verify this with colleague's who also run Fedora 41 on the same network. 

**To Reproduce**
1. Connect to WPA2 enterprise network

**Expected behavior**
Be able to connect to WPA2 network

**Operating environment (please complete the following information):**
 - OS: Fedora
 - Version: 41

**Token and application used (please complete the following information):**
 - PKCS11 Driver version: 0.5-4
 - Application NetworkManager

**Comment by simo5** [comment] 2024-11-21 13:33
Duplicate of #467 and #468

**Closed by simo5** 2024-11-21 13:33 UTC
