### ISSUE TITLE
PKCS11 provider with existing OpenSSL applications should not need modifications

### ISSUE THREAD

**Issue by dengert** [latchset/pkcs11-provider#201] opened 2023-02-17 17:05 UTC
**Describe the feature**

Existing OpenSSL applications that do not require any of the features of the pkcs11-provider  should not need modifications. 

What we have  learned so far:

- OpenSSL  3.0.0  when linked as a library does not appears to use env OPENSSL_CONFIG= by default.
- Most OpenSSL apps have an option:  `-config infile            Load a configuration file (this may load modules)`
- OpenSSL `dgst` application does not. There may be others.
- During testing adding `pkcs11-provider`  to default `openssl.cnf`  will allow `dgst` to use `pkcs11-provider`
- It appears that if `pkcs11-provider` is  defined  in `openssl.cnf` OpenSSL will consider it higher and use it before the default provider by design. 
- But if `pkcs11-provider`  is defined  in `openssl.cnf` other applications can fail. 

IMHO, the `pkcs11-provider` should only be used when requested by applications that understand how it is used. i.e. the OpenSSL apps. Other applications  or loadable modules that use libcrypto should not need modifications and continue is use the default LIBCTX. 

As simple way to disable `pkcs11-provider`:
```
PKCS11_PROVIDER_MODULE="disable.p11prov_module_init"
export PKCS11_PROVIDER_MODULE
```
This causes the provider to not initialize a PKCS11 module
This works with the script from  [@mouse7410](https://github.com/mouse07410) 
```
pkcs11-rsa-sign-demo.sh prov
OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

Testing pkcs11-provider

Using OpenSC PKCS#11 driver

This is not a CAC
Generating ephemeral file /tmp/derive.174296.text to test RSA-PSS signature...

openssl rand -engine rdrand -hex -out /tmp/derive.174296.text 5120
Engine "rdrand" set.

Signing file /tmp/derive.174296.text...
openssl dgst  -sign "pkcs11:model=PKCS%2315%20emulated;id=%02;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:48 -out /tmp/derive.174296.text.sig /tmp/derive.174296.text
Enter pass phrase for PKCS#11 Token (Slot 0 - Yubico YubiKey OTP+FIDO+CCID 00 00):

Signature for /tmp/derive.174296.text is stored in /tmp/derive.174296.text.sig

Verifying signature:
openssl dgst  -verify "pkcs11:model=PKCS%2315%20emulated;id=%02;type=public" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:48 -signature /tmp/derive.174296.text.sig  /tmp/derive.174296.text
Verified OK

Verifying signature using pkcs11-tool:
pkcs11-tool --module /opt/ossl-3.0.8/lib/opensc-pkcs11.so --verify -m SHA384-RSA-PKCS-PSS -y cert -d 02 --signature-file /tmp/derive.174296.text.sig -i /tmp/derive.174296.text
Using slot 0 with a present token (0x0)
Using signature algorithm SHA384-RSA-PKCS-PSS
PSS parameters: hashAlg=SHA384, mgf=MGF1-SHA384, salt_len=48 B
Signature is valid
```

[pkcs11-rsa-sign-demo.sh-diff.txt](https://github.com/latchset/pkcs11-provider/files/10768747/pkcs11-rsa-sign-demo.sh-diff.txt) includes some extra comments and setting of path to my OpenSSL-3.0.8 test environment but basically is the above 2 lines.
@mouse can you try this? 

This was using OpenSC without  https://github.com/OpenSC/OpenSC/pull/2712  and based on pkcs11-priovider It also avoids the double calling of C_Initialize as the provide never gets that far. 

**Expected behavior**

- No requirement of existing of applications, modules or libs that  use OpenSSL libcrypto to set a different libctx.
- OpenSSL apps should all have a -config option
- Should not load a PKCS11 module untill requested. 

Some of these are OpenSSL problems.

When in production the pkcs11-provider should not load a pkcs11 module untill it is actually called. This will avoid overhead and other problems for example system daemon that uses OpenSSL from loading PKCS11 with all its baggage eve what not gong to be used.

**Comment by beldmit** [comment] 2023-02-17 17:43
The proper env name is `OPENSSL_CONF`.
Do you mean static linkage?

All the applications load the config file on startup. The -config option is often either relic of old behavior or a way to provide supplementary options (e.g. req DN).

If you load only pkcs11 provider, you on't load default at all, and it's a problem. If you load both, you can set the preference order using properties: see https://www.openssl.org/docs/man3.0/man5/config.html (look for alg_section) and https://www.openssl.org/docs/man3.0/man7/property.html for syntax.

Hope this helps.

**Comment by simo5** [comment] 2023-02-17 17:57
I think I know where you are coming from @dengert but I think most of these requests are in direct conflict with the usefulness of using providers, and making access to pkcs11 modules more accessible.

*all* of what you describe is already possible by simply not enabling the pkcs11-provide in openssl.cnf and instead having applications explicitly load the provider via OSSL_PROVIDER_load()

The point of using providers though is to not have to change applications just because you want to use a differen cryptographic backend.
And the point of using pkcs11 uri is that you can have a an application use keys transparently, whether they are in files or in a cryptographic token without having to special case every single little application forever.

On the "What we have learned so far" part:

> OpenSSL 3.0.0 when linked as a library does not appears to use env OPENSSL_CONFIG= by default.

The env var is called OPENSSL_CONF and is source in the library code, if you used OPENSSL_CONFIG I guess that is why you failed to affect behavior?
In any case, this is not a fact.

> Most OpenSSL apps have an option: -config infile            Load a configuration file (this may load modules)
> OpenSSL dgst application does not. There may be others.

Ok but I think these facts are irrelevant, because the first "fact" is incorrect.

> During testing adding pkcs11-provider to default openssl.cnf will allow dgst to use pkcs11-provider

Yes, but you will need tpo ass provider=pkcs11 in the -propqqery argument of most openssl commands to do that.

> It appears that if pkcs11-provider is defined in openssl.cnf OpenSSL will consider it higher and use it before the default provider by design.

I saw the trace you showed me, but it never happened to me.
My experience is that OpenSSL always end up preferring the default provider, and I had to battle it quite a bit in the past to figure out how to make it actually use provider functions when available.
I do not think you can claim this as a fact without qualifying in what situation this happens. I am absolutely sure that this is not the norm.

> But if pkcs11-provider is defined in openssl.cnf other applications can fail.

The only application we saw fail is pkcs11-tool because it loads directly the same pkcs11 provider first thing, before anything else and it has no protection for loops. Which is quite a corner case.
In general, just loading a provider does not have other consequences on generic applications.
I am not saying this is not a problem, just qualifying that the case is very specific and directly related to the field of use.


Coming to your Expected behavior:
1. "No requirement of existing of applications, modules or libs that use OpenSSL libcrypto to set a different libctx."
 
- Applications do not need to change
- Modules or libraries *should always* use a private context when they do things like loading providers or causing other changes in behavior to openssl or need a potential different configuration to what the main application wants. This is regardless of this specific provider or the pkcs11 case.

2. "OpenSSL apps should all have a -config option"
- sure, open bugs against openssl ?

3. "Should not load a PKCS11 module untill requested"
- This may be doable, but requires a lot of work:
 
Currently, initialization is required in order to determine what mechanism are available in the token.
Based on then we construct which provider facilities to advertise to openssl, which query them later on in order to actually select an implementation to invoke.

Technically we can provide some of this information at a later time, however this is a complex area because OpenSSL also has internal caches, so it is not always clear what happens if you *change* at a later time what you offer.

I think we can work to transform the current initialization code to be more dynamic, this will have the benefit of allowing us to also handle dynamic changes in tokens, for systems where the token can be inserted/removed at will and multiple tokens may appear or disappear over time.

We could, for example have prompters that ask the user to insert a token when we get a CKR_TOKEN_NOT_PRESENT status in some conditions.

I am open to see specific issues open to any of these aspects.

Note that none of the changes here will ever discount the need for libraries/modules to use a private libctx from openssl, that is just good hygiene.

**Comment by simo5** [comment] 2023-02-17 18:01
@dengert, I welcome you opening a bug to "delay loading of pkcs11 modules", but I will otherwise close this bug because it is not actionable as is, and there is too much stuff in here that involve things that openssl 3.0 requires, implies, or otherwise forces that have nothing to do with the pkcs11-provider and that we cannot influence in the pkcs11-provider code.

**Comment by dengert** [comment] 2023-02-17 21:01
> The proper env name is OPENSSL_CONF.
Do you mean static linkage?

> All the applications load the config file on startup. The -config option is often either relic of old behavior or a way to provide supplementary options (e.g. req DN).

You right. 

> The only application we saw fail is pkcs11-tool because it loads directly the same pkcs11 provider first thing, before anything else and it has no protection for loops. Which is quite a corner case.
In general, just loading a provider does not have other consequences on generic applications.
I am not saying this is not a problem, just qualifying that the case is very specific and directly related to the field of use.

Yes  pkcs11-tool may be a corner case, it never expected OpenSSL would load a provider that loads the same pkcs11 module and calls C_initialize before pkcs11-tool could. 

OK I will open a new issue. Main issue is provider should not be loading PKCS modules if they will never be called, because the modules start looking for smartcards  which cause problems and overhead with some application that has nothing to do with smartcards. 

I am also pointing out RedHat would have a lot more clout with OpenSSL then I would on some of the OpenSSL issues.

**Comment by simo5** [comment] 2023-02-19 21:47
I think #202 practically addresses this, so closing.

**Closed by simo5** 2023-02-19 21:47 UTC
Labels: question
